import Head from "next/head";
import { VStack, Heading } from "@chakra-ui/react";
import NavBar from "../components/navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>TwitchDash</title>
        <meta
          name="Simple, lite easy to use Twitch Dashboard"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack p={4}>
        <Heading>
          Weclome To TwitchDash, If you're seeing this page you need to login
          with Twitch! This enables us to recieve the appropriate data from
          Twitch to then show you!
        </Heading>
      </VStack>
    </div>
  );
}
