import Head from "next/head";
import { VStack, Heading } from "@chakra-ui/react";
import NavBar from "../components/navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>TwitchDash</title>
        <meta
          name="Simple, lite easy to use Twitch Dashboard"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack p={4}>
        <Heading>
          Hi! If your viewing this page simply hit the button up top that says "Dashboard"!
        </Heading>
      </VStack>
    </div>
  );
}
